### ISSUE TITLE
Looks like you created multiple NinjaAPIs

### ISSUE THREAD

**Issue by pitsolu** [mugartec/django-ninja-auth#2]
Hi, Got an error: 

Django==4.0.1
django-ninja==0.13.2
django-ninja-auth==0.1.5
pytest==6.2.5
pytest-django==4.5.2

ninja.errors.ConfigError: Looks like you created multiple NinjaAPIs
To let ninja distinguish them you need to set either unique version or url_namespace
 - NinjaAPI(..., version='2.0.0')
 - NinjaAPI(..., urls_namespace='otherapi')
Already registered: ['api-1.0.0']

**Comment by smyja** [comment]
Have you resolved this 

> Hi, Got an error:
> 
> Django==4.0.1 django-ninja==0.13.2 django-ninja-auth==0.1.5 pytest==6.2.5 pytest-django==4.5.2
> 
> ninja.errors.ConfigError: Looks like you created multiple NinjaAPIs To let ninja distinguish them you need to set either unique version or url_namespace
> 
> * NinjaAPI(..., version='2.0.0')
> * NinjaAPI(..., urls_namespace='otherapi')
>   Already registered: ['api-1.0.0']

**Comment by pitsolu** [comment]
@Smyja Take a look at this [buupass-challenge](https://github.com/samweru/buupass-challenge) may help you.

**Comment by mugartec** [comment]
@pitsolu django-ninja-auth does not create a NinjaAPI, only the router. Your project should be creating the API(s); how are you doing this? [Here](https://github.com/mugartec/django-ninja-auth-app-backend) is a complete working example.

**Comment by pitsolu** [comment]
@mugartec Thanks for your response. I solved the issue.

Is there a way of creating permissions on routes with decorators? Something like this @\api.permissions

**Comment by mugartec** [comment]
@pitsolu I don't think there's a django-ninja specific way of doing so, but for permissions you could directly use [Django's @permission_required](https://docs.djangoproject.com/en/4.0/topics/auth/default/#the-permission-required-decorator). Something like
```python
@api.get('/route')
@permission_required('app.permission', raise_exception=True)
def view(request):
    return <something>
```

**Edit**: added `raise_exception=True` to return 403 instead of 302.

**Comment by pitsolu** [comment]
@mugartec thanks! This has been very helpful. Continue the good work.

**Comment by peterflat** [comment]
Just adding here for posterity.

In Django in your `urls.py` file, if you import your Ninja api urls and then later/lower in the file reference a view that doesn't exist, Ninja can swallow the error and you will see this instead of the actual raised error.

**Comment by jlalfonso21** [comment]
> Just adding here for posterity.
> 
> In Django in your `urls.py` file, if you import your Ninja api urls and then later/lower in the file reference a view that doesn't exist, Ninja can swallow the error and you will see this instead of the actual raised error.

yeah, this is the issue in my case, any long term solution already?
