### ISSUE TITLE
No auth token is given back for future authentication requests?

### ISSUE THREAD

**Issue by dizzydes** [mugartec/django-ninja-auth#5]
![Screenshot 2022-12-17 at 19 39 51](https://user-images.githubusercontent.com/10514807/208267062-e9eabb55-a502-4474-b14b-3220a8da2a63.png)
In the docs it leaves a field for adding this so I assume it should exist?

**Comment by mugartec** [comment]
Just retaking the project (rather late, sorry). No, this package is only for cookie-based authentication. Logging in will set a cookie and you'll be logged in from that point on. Your session id token is stored in your browser as a cookie. It's intended to interact with a front-end.
